In [1]:
import pandas as pd

df = pd.DataFrame({
    "name": ["A", "B", "C", "D"],
    "age": [20, 25, 30, 35],
    "score": [80, 65, 90, 70]
}, index=["a", "b", "c", "d"])
df

  name  age  score
a    A   20     80
b    B   25     65
c    C   30     90
d    D   35     70

In [2]:
df.loc["b"]

name      B
age      25
score    65
Name: b, dtype: object

In [3]:
df.iloc[0:2, 0:2]

  name  age
a    A   20
b    B   25

In [4]:
df[df["age"] < 30]

  name  age  score
a    A   20     80
b    B   25     65

In [5]:
df.query("age >= 30 and score >70")

  name  age  score
c    C   30     90

In [6]:
df.sort_values("score")

  name  age  score
b    B   25     65
d    D   35     70
a    A   20     80
c    C   30     90

In [14]:
#merge
df2 = pd.DataFrame({
    "name": ["E", "F", "G", "H"],
    "age": [1500, 75, 60, 40],
    "score": [80, 65, 90, 70]
}, index=["a", "b", "c", "d"])
df_mrg = pd.merge(df,df2,how="outer")
df_mrg

  name   age  score
0    A    20     80
1    B    25     65
2    C    30     90
3    D    35     70
4    E  1500     80
5    F    75     65
6    G    60     90
7    H    40     70

In [19]:
#concat
cat = pd.concat([df,df2],axis=0)
cat

  name   age  score
a    A    20     80
b    B    25     65
c    C    30     90
d    D    35     70
a    E  1500     80
b    F    75     65
c    G    60     90
d    H    40     70

In [26]:
df["date"] = [
    "2026-01-05",
    "2026-01-06",
    "2026-02-10",
    "2026-02-15"
]
df
df["date"] = pd.to_datetime(df["date"])
df

  name  age  score       date
a    A   20     80 2026-01-05
b    B   25     65 2026-01-06
c    C   30     90 2026-02-10
d    D   35     70 2026-02-15